name: git-workflow-enable

on:
  push:
    branches: 
      - master

# on:
#   schedule:
#     - cron: 0 0 1 * *

jobs:
  git-workflow-enable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Enable workflows
        run: |
          for workflow in $(cat workflows.txt); do
            curl -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.PAT}}" \
              --url "${workflow}"
          done